{
  "__comment": "Augmented skeleton_config for deterministic synthetic issue text. Tuned for a local cached Hugging Face t5-small. Extend cautiously.",
  "model": {
    "name": "t5-small",
    "task_prefix": "paraphrase: ",
    "max_new_tokens": 64,
    "temperature": 0.0,
    "top_p": 1.0,
    "do_sample": false,
    "repetition_penalty": 1.05,
    "seed": 42,
    "eos_token": "</s>",
    "pad_token": "<pad>"
  },

  "normalization": {
    "lowercase_ratio_target": 0.9,
    "strip_whitespace": true,
    "collapse_spaces": true,
    "dedupe_punctuation": true,
    "ensure_period_terminal": true,
    "joiner": "_",
    "snake_case_fields": ["verbs","qualifiers","severities"],
    "keep_casing_for": ["project_keys","env","code","error_class","branch","version"]
  },

  "constraints": {
    "max_tokens_per_output": 96,
    "min_tokens_per_output": 12,
    "ban_repeated_bigrams": true,
    "forbid_substrings": ["lorem ipsum", "foobar", "dummy text"],
    "soft_wrap_width": 120
  },

  "synonyms": {
    "verbs": {
      "fails": ["breaks", "errors"],
      "crashes": ["stops", "faults"],
      "hangs": ["stalls", "locks"],
      "returns": ["yields", "sends"],
      "observed": ["seen", "noticed"],
      "timeouts": ["expires", "times_out"],
      "retries": ["re-attempts", "tries_again"],
      "rolls_back": ["reverts", "undoes"],
      "deploys": ["releases", "rolls_out"]
    },
    "qualifiers": {
      "slightly": ["marginally", "lightly"],
      "severely": ["critically", "badly"],
      "unexpected": ["surprising", "unplanned"],
      "intermittent": ["sporadic", "occasional"],
      "consistent": ["repeatable", "stable"]
    },
    "severities": {
      "critical": ["blocking", "severe"],
      "high": ["major", "elevated"],
      "medium": ["moderate", "normal"],
      "low": ["minor", "reduced"]
    }
  },

  "filler_phrases": [
    "It seems that",
    "We noticed that",
    "Please note that",
    "In other words",
    "For reference",
    "As a result",
    "In this case",
    "Specifically"
  ],

  "voice_patterns": {
    "passive_to_active": [
      { "pattern": "\\bwas (?P<verb>\\w+ed) by (?P<actor>[^\\.;\\n]+)", "replacement": "{actor} {verb}" },
      { "pattern": "\\bwere (?P<verb>\\w+ed) by (?P<actor>[^\\.;\\n]+)", "replacement": "{actor} {verb}" }
    ],
    "active_to_passive": [
      { "pattern": "\\b(?P<actor>[A-Za-z0-9_ /-]+) (?P<verb>fails|crashes|blocks|breaks)", "replacement": "was {verb} by {actor}" },
      { "pattern": "\\b(?P<actor>[A-Za-z0-9_ /-]+) (?P<verb>denies|rejects|throttles)", "replacement": "was {verb} by {actor}" }
    ],
    "style": {
      "prefer_present_simple": true,
      "allow_past_simple": true,
      "avoid_future_modal": true
    }
  },

  "slot_weights": {
    "templates": {
      "{component}: {verb} {object} when {condition}": 3,
      "[{scope}] {component} fails on {env} with {error_class} ({code})": 4,
      "{component} {verb_past} after {action} in {env}": 2,
      "Regression: {object} {verb} on {branch} since {version}": 2
    },
    "severity_bias": { "critical": 0.2, "high": 0.3, "medium": 0.3, "low": 0.2 },
    "hourly_weight": [2,1,1,1,1,1,2,4,6,8,9,8,7,7,7,8,9,8,6,5,4,3,3,2]
  },

  "surface_realization": {
    "article_rules": [
      { "pattern": "\\b(api|sdk|sso)\\b", "article": "the" }
    ],
    "hyphenate_compounds": true,
    "ensure_code_brackets_for_endpoints": true,
    "http_status_format": "numeric_string",
    "join_scope_prefix": true
  },

  "sampling_masks": {
    "object_by_scope": {
      "api": ["API_endpoint","REST_controller","GraphQL_resolver","gRPC_endpoint","rate_limiter","authentication"],
      "ui": ["UI_component","frontend_router","theme_manager","accessibility_layer","client_state","CSS_styles"],
      "db": ["schema_migration","transaction_manager","locking_mechanism","database_connection","ORM_layer","index_missing"],
      "infra": ["CDN_integration","load_balancer","api_gateway","container_recycled","pod_evicted","TLS_handshake"]
    },
    "error_class_by_code": {
      "504": ["GatewayTimeoutException","ResponseTimeout","HttpTimeoutException"],
      "503": ["ServiceUnavailableException","GrpcUnavailable","ServerException"],
      "ECONNRESET": ["ConnectionResetError","SocketException","NetworkError"],
      "401": ["UnauthorizedException","AuthenticationException","UnauthorizedAccessException"]
    },
    "env_defaults": {
      "ui": ["Chrome_126","Firefox_118","Safari_17"],
      "api": ["Node_20","Java_17","Python_3.11"],
      "infra": ["Kubernetes_1.28","Docker_25","Ubuntu_22.04"]
    }
  },

  "postprocessors": [
    { "name": "collapse_spaces", "apply": true },
    { "name": "trim_outer_quotes", "apply": true },
    { "name": "ensure_period_terminal", "apply": true },
    { "name": "dedupe_codes_in_parentheses", "apply": true }
  ],

  "guards": {
    "max_codes_per_line": 1,
    "max_endpoints_per_line": 2,
    "ban_mixed_http_and_signal": true,
    "allowed_branches_regex": "^(main|master|dev(elop)?|staging|prod(uction)?|release\\/.*|hotfix\\/.*|feature\\/.*|bugfix\\/.*)$"
  },

  "placeholders": {
    "endpoint_format": "/v{major}/{area}/{resource}",
    "user_handle_format": "@{user}",
    "iso_date_format": "YYYY-MM-DD"
  }
}

