on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: triage
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres" --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:7
        ports: ['6379:6379']
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/triage
      REDIS_URL: redis://localhost:6379/0
      GITHUB_WEBHOOK_SECRET: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: static checks
        run: |
          python -m compileall api worker eval
      - name: Validate sandbox compose
        run: docker compose -f ops/docker-compose.sandbox.yml config
      - name: API unit smoke
        run: |
          uvicorn api.main:app --help
